import { ImageIcon } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatDateTime } from "@/lib/utils";
import type { ScreenshotArtifact } from "@/lib/types";

export function ScreenshotGallery({ screenshots }: Readonly<{ screenshots: readonly ScreenshotArtifact[] }>): JSX.Element {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Screenshots</CardTitle>
        <CardDescription>Evidence generated by browser automation runs</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid gap-3 md:grid-cols-2">
          {screenshots.map((screenshot) => (
            <div key={screenshot.id} className="rounded-md border bg-background p-3">
              <div className="flex aspect-video items-center justify-center rounded-md bg-muted">
                <ImageIcon className="h-8 w-8 text-muted-foreground" aria-hidden="true" />
              </div>
              <div className="mt-3 text-sm font-medium">{screenshot.title}</div>
              <div className="mt-1 text-xs text-muted-foreground">{formatDateTime(screenshot.capturedAt)}</div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
