"""Contracts for isolated QA execution sandboxes."""

from datetime import datetime, timezone
from enum import StrEnum
from pathlib import Path
from typing import Any
from uuid import UUID, uuid4

from pydantic import Field

from core.contracts.base import ContractBaseModel, TraceMetadata


class SandboxBrowserEngine(StrEnum):
    """Browser engines supported by the sandbox boundary."""

    PLAYWRIGHT = "playwright"
    SELENIUM = "selenium"


class SandboxExecutionStatus(StrEnum):
    """Sandbox execution status."""

    PENDING = "pending"
    RUNNING = "running"
    PASSED = "passed"
    FAILED = "failed"
    RETRYING = "retrying"


class SandboxArtifactKind(StrEnum):
    """Execution artifact kinds emitted by the QA sandbox."""

    SCREENSHOT = "screenshot"
    VIDEO = "video"
    LOG = "log"
    TRACE = "trace"
    TEST_EVIDENCE = "test_evidence"


class SandboxIsolationMode(StrEnum):
    """Sandbox isolation deployment modes."""

    LOCAL_PROCESS = "local_process"
    DOCKER = "docker"
    KUBERNETES = "kubernetes"


class SandboxStepAction(StrEnum):
    """Browser test step actions."""

    NAVIGATE = "navigate"
    CLICK = "click"
    FILL = "fill"
    ASSERT_VISIBLE = "assert_visible"
    SCREENSHOT = "screenshot"
    RECORD_VIDEO = "record_video"
    LOG = "log"


class SandboxResourceLimits(ContractBaseModel):
    """Resource limits for Docker/Kubernetes-ready execution."""

    timeout_seconds: int = Field(default=120, ge=1)
    max_retries: int = Field(default=1, ge=0)
    cpu_limit: str | None = "1"
    memory_limit: str | None = "1Gi"
    network_enabled: bool = True


class SandboxExecutionConfig(ContractBaseModel):
    """Execution configuration for a browser sandbox session."""

    engine: SandboxBrowserEngine
    isolation_mode: SandboxIsolationMode = SandboxIsolationMode.LOCAL_PROCESS
    headless: bool = True
    docker_image: str | None = None
    kubernetes_namespace: str | None = None
    browser_name: str = "chromium"
    resource_limits: SandboxResourceLimits = Field(default_factory=SandboxResourceLimits)
    metadata: dict[str, Any] = Field(default_factory=dict)


class SandboxSession(ContractBaseModel):
    """Isolated browser execution session."""

    id: UUID = Field(default_factory=uuid4)
    agent_name: str = "qa"
    execution_id: UUID = Field(default_factory=uuid4)
    thread_id: str | None = None
    root_path: Path
    artifact_path: Path
    browser_profile_path: Path
    config: SandboxExecutionConfig
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)


class SandboxStep(ContractBaseModel):
    """Single secure sandbox test step."""

    action: SandboxStepAction
    target: str | None = None
    value: str | None = None
    description: str = Field(min_length=1)
    metadata: dict[str, Any] = Field(default_factory=dict)


class SandboxArtifact(ContractBaseModel):
    """Artifact generated by sandbox execution."""

    id: UUID = Field(default_factory=uuid4)
    kind: SandboxArtifactKind
    path: Path
    name: str = Field(min_length=1)
    description: str = Field(min_length=1)
    content_type: str | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)


class SandboxStepResult(ContractBaseModel):
    """Result of one sandbox step."""

    step: SandboxStep
    success: bool
    message: str = ""
    artifacts: tuple[SandboxArtifact, ...] = Field(default_factory=tuple)
    metadata: dict[str, Any] = Field(default_factory=dict)


class SandboxExecutionResult(ContractBaseModel):
    """Complete QA sandbox execution result."""

    session: SandboxSession
    status: SandboxExecutionStatus
    trace: TraceMetadata = Field(default_factory=TraceMetadata)
    attempts: int = Field(default=1, ge=1)
    step_results: tuple[SandboxStepResult, ...] = Field(default_factory=tuple)
    artifacts: tuple[SandboxArtifact, ...] = Field(default_factory=tuple)
    logs: tuple[str, ...] = Field(default_factory=tuple)
    errors: tuple[str, ...] = Field(default_factory=tuple)
    metadata: dict[str, Any] = Field(default_factory=dict)

