apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-agent-delivery-staging
resources:
  - ../../base
replicas:
  - name: multi-agent-backend
    count: 1
  - name: multi-agent-frontend
    count: 1

