import type { DashboardSnapshot } from "./types";

const now = new Date("2026-05-21T15:40:00-05:00");

function minutesAgo(minutes: number): string {
  return new Date(now.getTime() - minutes * 60_000).toISOString();
}

export const mockDashboardSnapshot: DashboardSnapshot = {
  workflowId: "wf-enterprise-001",
  agents: [
    {
      key: "ba",
      name: "Business Analyst",
      status: "completed",
      currentTask: "Story contract generated",
      lastEventAt: minutesAgo(48),
      retryCount: 0,
    },
    {
      key: "architect",
      name: "Architect",
      status: "completed",
      currentTask: "Architecture context approved",
      lastEventAt: minutesAgo(37),
      retryCount: 0,
    },
    {
      key: "developer",
      name: "Developer",
      status: "running",
      currentTask: "Generating implementation plan",
      lastEventAt: minutesAgo(4),
      retryCount: 1,
    },
    {
      key: "qa",
      name: "QA",
      status: "idle",
      currentTask: "Waiting for developer output",
      lastEventAt: minutesAgo(9),
      retryCount: 0,
    },
    {
      key: "docs",
      name: "Docs",
      status: "idle",
      currentTask: "Waiting for QA approval",
      lastEventAt: minutesAgo(18),
      retryCount: 0,
    },
    {
      key: "pr",
      name: "PR",
      status: "idle",
      currentTask: "Draft pending",
      lastEventAt: minutesAgo(18),
      retryCount: 0,
    },
  ],
  stages: [
    { id: "ba", label: "BA", status: "completed", completedAt: minutesAgo(48), metadata: { stories: 3 } },
    { id: "architect", label: "Architect", status: "completed", completedAt: minutesAgo(37), metadata: { decisions: 5 } },
    { id: "developer", label: "Developer", status: "running", startedAt: minutesAgo(35), metadata: { files: 12 } },
    { id: "qa", label: "QA", status: "pending", metadata: { gates: 4 } },
    { id: "docs", label: "Docs", status: "pending", metadata: { artifacts: 2 } },
    { id: "pr", label: "PR", status: "pending", metadata: { provider: "GitLab" } },
  ],
  events: [
    {
      id: "evt-1",
      type: "agent_started",
      agent: "developer",
      message: "Developer agent isolated context loaded.",
      timestamp: minutesAgo(35),
      severity: "info",
    },
    {
      id: "evt-2",
      type: "retry_started",
      agent: "developer",
      message: "Retry policy started after output contract validation warning.",
      timestamp: minutesAgo(7),
      severity: "medium",
    },
    {
      id: "evt-3",
      type: "agent_started",
      agent: "qa",
      message: "QA gate queued for execution.",
      timestamp: minutesAgo(3),
      severity: "info",
    },
  ],
  timeline: [
    {
      id: "tl-1",
      title: "Story package accepted",
      description: "BA output contract validated with acceptance criteria.",
      timestamp: minutesAgo(52),
      status: "completed",
    },
    {
      id: "tl-2",
      title: "Architecture context assembled",
      description: "Dependency graph and constraints handed to developer runtime.",
      timestamp: minutesAgo(37),
      status: "completed",
    },
    {
      id: "tl-3",
      title: "Developer generation in progress",
      description: "Structured implementation output is being generated.",
      timestamp: minutesAgo(4),
      status: "running",
    },
    {
      id: "tl-4",
      title: "QA execution pending",
      description: "Unit, integration, browser, and evidence collection gates are queued.",
      timestamp: minutesAgo(1),
      status: "pending",
    },
  ],
  logs: [
    {
      id: "log-1",
      timestamp: minutesAgo(9),
      level: "info",
      source: "runtime.developer",
      message: "PromptBuilder composed rules: gravity, anti-gravity, standards, testing, security.",
    },
    {
      id: "log-2",
      timestamp: minutesAgo(7),
      level: "warning",
      source: "runtime.validator",
      message: "Output contract required retry: missing test generation section.",
    },
    {
      id: "log-3",
      timestamp: minutesAgo(4),
      level: "info",
      source: "graph.supervisor",
      message: "Developer node resumed with retry metadata.",
    },
  ],
  qaReport: {
    executionId: "qa-run-001",
    status: "running",
    coveragePercent: 82,
    unitTests: 48,
    integrationTests: 12,
    browserTests: 6,
    bugs: [
      {
        id: "bug-001",
        title: "QA gate waiting for executable artifact",
        severity: "info",
        status: "triaged",
        evidence: "No blocking failure; QA is queued after developer output validation.",
      },
    ],
    screenshots: [
      {
        id: "shot-001",
        title: "Dashboard shell smoke capture",
        path: "/placeholder-screenshot.svg",
        capturedAt: minutesAgo(2),
      },
    ],
  },
  docs: [
    {
      id: "doc-1",
      title: "Architecture Decision Log",
      status: "generated",
      updatedAt: minutesAgo(22),
      summary: "Captures orchestration, runtime, context, governance, and streaming decisions.",
    },
    {
      id: "doc-2",
      title: "Developer Runtime Notes",
      status: "draft",
      updatedAt: minutesAgo(13),
      summary: "Summarizes prompt composition, context boundaries, and retry-safe execution.",
    },
  ],
  pullRequest: {
    id: "pr-1042",
    title: "Draft: multi-agent runtime foundation",
    status: "draft",
    branch: "feature/runtime-foundation",
    target: "main",
    changedFiles: 38,
    riskLevel: "medium",
    summary: "Includes contracts, runtime, memory, graph orchestration, QA system, governance, streaming, and API shell.",
  },
  approvals: [
    {
      approvalId: "approval-001",
      workflowId: "wf-enterprise-001",
      gateType: "qa_override",
      status: "pending",
      title: "Approve QA override",
      description: "QA rejection can be overridden only by a delivery lead with risk acceptance.",
      requestedBy: "qa",
      requiredReviewers: [{ reviewerId: "lead-1", displayName: "Delivery Lead", role: "lead" }],
      pauseReason: "qa_override_required",
      createdAt: minutesAgo(2),
    },
    {
      approvalId: "approval-002",
      workflowId: "wf-enterprise-001",
      gateType: "pr_approval",
      status: "approved",
      title: "PR draft approval",
      description: "Manual review accepted the generated PR summary.",
      requestedBy: "pr",
      requiredReviewers: [{ reviewerId: "arch-1", displayName: "Principal Architect", role: "architect" }],
      pauseReason: "pr_review_required",
      createdAt: minutesAgo(20),
      decidedAt: minutesAgo(14),
      decisionReason: "Summary and test evidence are complete.",
    },
  ],
  observability: {
    workflow: {
      workflowId: "wf-enterprise-001",
      durationMs: 286000,
      agentCount: 6,
      retries: 1,
      failures: 0,
      qaRejectionRate: 0.25,
      tokenUsage: { promptTokens: 12400, completionTokens: 4300, totalTokens: 16700 },
      promptTelemetry: { messageCount: 42, characterCount: 58800, estimatedTokens: 14700 },
    },
    agents: [
      {
        agentName: "developer",
        executionsStarted: 2,
        executionsCompleted: 1,
        failures: 0,
        retries: 1,
        qaRejections: 0,
        averageExecutionTimeMs: 124000,
        tokenUsage: { promptTokens: 6200, completionTokens: 2400, totalTokens: 8600 },
        promptTelemetry: { messageCount: 18, characterCount: 28400, estimatedTokens: 7100 },
      },
      {
        agentName: "qa",
        executionsStarted: 1,
        executionsCompleted: 1,
        failures: 0,
        retries: 0,
        qaRejections: 1,
        averageExecutionTimeMs: 76000,
        tokenUsage: { promptTokens: 3100, completionTokens: 900, totalTokens: 4000 },
        promptTelemetry: { messageCount: 11, characterCount: 13200, estimatedTokens: 3300 },
      },
    ],
    metrics: [
      "agent_execution_duration_ms",
      "agent_retries_total",
      "agent_failures_total",
      "qa_rejections_total",
      "workflow_duration_ms",
      "tokens_total",
      "prompt_size_estimated_tokens",
    ],
    exporters: {
      opentelemetryReady: true,
      datadogReady: true,
      prometheusReady: true,
      grafanaReady: true,
    },
  },
  governance: {
    documents: [
      {
        id: "gov-global-gravity",
        scope: "global",
        kind: "gravity",
        name: "Global Gravity Rules",
        markdown: "- Always preserve agent boundaries.\n- Always use typed contracts.\n- Always keep orchestration separate from execution.",
        version: 3,
        updatedBy: "platform-admin",
        updatedAt: minutesAgo(6),
      },
      {
        id: "gov-dev-standards",
        scope: "agent",
        kind: "coding_standards",
        name: "Developer Coding Standards",
        agentName: "developer",
        markdown: "- Use Clean Architecture boundaries.\n- Generate focused tests for risky changes.\n- Keep prompts modular.",
        version: 2,
        updatedBy: "tech-lead",
        updatedAt: minutesAgo(12),
      },
      {
        id: "gov-qa-policy",
        scope: "agent",
        kind: "qa_policy",
        name: "QA Policy",
        agentName: "qa",
        markdown: "- Capture evidence for every critical defect.\n- Classify severity using impact and reproducibility.\n- Prefer autonomous browser validation when UI behavior changes.",
        version: 4,
        updatedBy: "qa-lead",
        updatedAt: minutesAgo(18),
      },
    ],
    versions: [
      {
        id: "gov-version-1",
        documentId: "gov-global-gravity",
        version: 1,
        markdown: "- Always preserve agent boundaries.",
        changedBy: "system",
        changeSummary: "Initial global defaults.",
        createdAt: minutesAgo(80),
      },
      {
        id: "gov-version-2",
        documentId: "gov-global-gravity",
        version: 2,
        markdown: "- Always preserve agent boundaries.\n- Always use typed contracts.",
        changedBy: "platform-admin",
        changeSummary: "Added contract requirement.",
        createdAt: minutesAgo(40),
      },
      {
        id: "gov-version-3",
        documentId: "gov-global-gravity",
        version: 3,
        markdown: "- Always preserve agent boundaries.\n- Always use typed contracts.\n- Always keep orchestration separate from execution.",
        changedBy: "platform-admin",
        changeSummary: "Added orchestration boundary.",
        createdAt: minutesAgo(6),
      },
    ],
  },
  workspace: {
    conversations: [
      {
        id: "chat-001",
        title: "Implement approval-gated QA workflow",
        updatedAt: minutesAgo(1),
        attachments: [
          { id: "att-001", kind: "markdown", name: "story.md", sizeBytes: 842 },
          { id: "att-002", kind: "git_repository", name: "platform repository", uri: "https://gitlab.com/example/platform.git", sizeBytes: 42 },
          { id: "att-003", kind: "url", name: "design notes", uri: "https://example.com/design", sizeBytes: 26 },
        ],
        messages: [
          {
            id: "msg-001",
            role: "user",
            content: "Use the attached story and repository reference to trigger the delivery workflow.",
            attachmentIds: ["att-001", "att-002", "att-003"],
            createdAt: minutesAgo(8),
          },
          {
            id: "msg-002",
            role: "assistant",
            content: "**Workflow triggered.**\n\nBA is preparing the story package and I will stream progress here.",
            attachmentIds: [],
            workflowId: "wf-enterprise-001",
            createdAt: minutesAgo(7),
          },
          {
            id: "msg-003",
            role: "workflow",
            content: "Developer is running with repository context. QA sandbox is queued.",
            attachmentIds: [],
            workflowId: "wf-enterprise-001",
            createdAt: minutesAgo(2),
          },
        ],
      },
    ],
  },
  visualization: {
    workflowId: "wf-enterprise-001",
    status: "running",
    activeAgent: "developer",
    progressPercent: 46,
    durationMs: 286000,
    nodes: [
      { id: "ba", label: "BA", agentName: "ba", status: "completed", startedAt: minutesAgo(56), completedAt: minutesAgo(48), durationMs: 480000, retryCount: 0, metadata: { dependencyIndex: 0 } },
      { id: "architect", label: "Architect", agentName: "architect", status: "completed", startedAt: minutesAgo(47), completedAt: minutesAgo(37), durationMs: 600000, retryCount: 0, metadata: { dependencyIndex: 1 } },
      { id: "developer", label: "Developer", agentName: "developer", status: "running", startedAt: minutesAgo(35), durationMs: 2100000, retryCount: 1, metadata: { dependencyIndex: 2 } },
      { id: "qa", label: "QA", agentName: "qa", status: "pending", retryCount: 0, metadata: { dependencyIndex: 3 } },
      { id: "docs", label: "Docs", agentName: "docs", status: "pending", retryCount: 0, metadata: { dependencyIndex: 4 } },
      { id: "pr", label: "PR", agentName: "pr", status: "pending", retryCount: 0, metadata: { dependencyIndex: 5 } },
    ],
    edges: [
      { source: "ba", target: "architect", label: "requirements", isLoop: false, metadata: {} },
      { source: "architect", target: "developer", label: "architecture", isLoop: false, metadata: {} },
      { source: "developer", target: "qa", label: "implementation", isLoop: false, metadata: {} },
      { source: "qa", target: "docs", label: "approved", condition: "qa_passed", isLoop: false, metadata: {} },
      { source: "qa", target: "developer", label: "rejected", condition: "qa_failed", isLoop: true, metadata: {} },
      { source: "docs", target: "pr", label: "documentation", isLoop: false, metadata: {} },
    ],
    timeline: [
      { id: "vt-1", eventType: "agent_started", agentName: "ba", message: "BA started.", timestamp: minutesAgo(56), metadata: {} },
      { id: "vt-2", eventType: "agent_completed", agentName: "ba", message: "BA completed.", timestamp: minutesAgo(48), durationMs: 480000, metadata: {} },
      { id: "vt-3", eventType: "retry_started", agentName: "developer", message: "Developer retry started.", timestamp: minutesAgo(7), metadata: { retry: 1 } },
    ],
    mermaid: `flowchart LR
  BA["BA (completed)"] --> Architect["Architect (completed)"]
  Architect --> Developer["Developer (running)"]
  Developer --> QA["QA (pending)"]
  QA -->|approved| Docs["Docs (pending)"]
  QA -->|rejected retry| Developer
  Docs --> PR["PR (pending)"]`,
    metadata: {
      eventCount: 3,
      retryCount: 1,
      qaLoopCount: 0,
      websocketChannel: "/ws/workflows/wf-enterprise-001/telemetry",
    },
  },
  mermaid: `flowchart LR
  BA["BA"] --> Architect["Architect"]
  Architect --> Developer["Developer"]
  Developer --> QA["QA"]
  QA -->|approved| Docs["Docs"]
  QA -->|rejected| Developer
  Docs --> PR["PR"]`,
};
